name: Compile and test

on: [push, pull_request]

env:
  CLONE_NAME: maliput-multilane
  PACKAGE_NAME: maliput_multilane
  ROS_DISTRO: dashing
  ROS_WS: ros_ws

jobs:
  compile_and_test:
    name: Compile and test
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
      with:
        path: ${{ env.ROS_WS }}/src/${{ env.PACKAGE_NAME }}
    # clone private dependencies
    - uses: actions/checkout@v2
      with:
        repository: ToyotaResearchInstitute/maliput
        path: ${{ env.ROS_WS }}/src/maliput
        token: ${{ secrets.MALIPUT_TOKEN }}
    - uses: actions/checkout@v2
      with:
        repository: ToyotaResearchInstitute/drake-vendor
        path: ${{ env.ROS_WS }}/src/drake_vendor
        token: ${{ secrets.MALIPUT_TOKEN }}
    # use setup-ros2 action to get vcs, rosdep, and colcon
    - uses: ros-tooling/setup-ros2@0.0.11
    # clone public dependencies
    - name: vcs import
      shell: bash
      working-directory: ${{runner.workspace}}/${{ env.CLONE_NAME }}/${{ env.ROS_WS }}
      run: vcs import src < src/${PACKAGE_NAME}/.github/dependencies.repos
    - name: colcon graph
      shell: bash
      working-directory: ${{runner.workspace}}/${{ env.CLONE_NAME }}/${{ env.ROS_WS }}
      run: colcon graph
    - name: rosdep install
      shell: bash
      working-directory: ${{runner.workspace}}/${{ env.CLONE_NAME }}/${{ env.ROS_WS }}
      run: |
        rosdep update;
        rosdep install  -i -y --rosdistro ${ROS_DISTRO} --skip-keys "pybind11" --from-paths src
    - name: colcon build
      shell: bash
      working-directory: ${{runner.workspace}}/${{ env.CLONE_NAME }}/${{ env.ROS_WS }}
      run: |
        . /opt/ros/${ROS_DISTRO}/setup.bash;
        colcon build --packages-up-to ${PACKAGE_NAME} --event-handlers=console_direct+;
    - name: colcon test
      shell: bash
      working-directory: ${{runner.workspace}}/${{ env.CLONE_NAME }}/${{ env.ROS_WS }}
      run: |
        . /opt/ros/${ROS_DISTRO}/setup.bash;
        colcon test --packages-select ${PACKAGE_NAME} --event-handlers=console_direct+;
        colcon test-result --verbose;
