name: Compile and test with asan, tsan and ubsan

on: [push, pull_request]

env:
  PACKAGE_NAME: maliput_dragway
  ROS_DISTRO: dashing
  ROS_WS: maliput_ws

jobs:
  compile_and_test:
    name: Compile and test
    runs-on: ubuntu-18.04
    container:
      image: ubuntu:18.04
    strategy:
      matrix:
        sanitizer: [asan, ubsan, tsan]
        include:
          - sanitizer: asan
            COMPILER_FLAG: ' -DADDRESS_SANITIZER=On'
          - sanitizer: tsan
            COMPILER_FLAG: ' -DTHREAD_SANITIZER=On'
          - sanitizer: ubsan
            COMPILER_FLAG: ' -DUNDEFINED_SANITIZER=On'
    env:
      DO_BUILD: ${{ github.event_name == 'pull_request' || ( github.event_name == 'push' && github.ref == 'master') }}
      CC: clang
      CXX: clang++
      LINKER_PATH: /usr/bin/llvm-ld
    steps:
    - run: echo ${DO_BUILD}
    - uses: actions/checkout@v2
      if: ${{ env.DO_BUILD == 'true' }}
      with:
        path: ${{ env.ROS_WS }}/src/${{ env.PACKAGE_NAME }}
    # clone private dependencies
    - uses: actions/checkout@v2
      if: ${{ env.DO_BUILD == 'true' }}
      with:
        repository: ToyotaResearchInstitute/maliput
        path: ${{ env.ROS_WS }}/src/maliput
        token: ${{ secrets.MALIPUT_TOKEN }}
    - uses: actions/checkout@v2
      if: ${{ env.DO_BUILD == 'true' }}
      with:
        repository: ToyotaResearchInstitute/drake-vendor
        path: ${{ env.ROS_WS }}/src/drake_vendor
        token: ${{ secrets.MALIPUT_TOKEN }}
    - uses: actions/checkout@v2
      if: ${{ env.DO_BUILD == 'true' }}
      with:
        repository: ToyotaResearchInstitute/dsim-repos-index
        path: dsim-repos-index
        token: ${{ secrets.MALIPUT_TOKEN }}
    # use setup-ros action to get vcs, rosdep, and colcon
    - uses: ros-tooling/setup-ros@0.0.25
      if: ${{ env.DO_BUILD == 'true' }}
    # install drake_vendor prereqs using dsim-repos-index/tools/prereqs.lib
    - name: install drake_vendor prereqs
      if: ${{ env.DO_BUILD == 'true' }}
      shell: bash
      working-directory: ${{ env.ROS_WS }}/src/drake_vendor
      run: ${GITHUB_WORKSPACE}/dsim-repos-index/tools/prereqs-install -t drake .
    - name: clang 8 install
      if: ${{ env.DO_BUILD == 'true' }}
      shell: bash
      run: ${{ env.ROS_WS }}/src/${{ env.PACKAGE_NAME }}/.github/clang_suite_installation.sh
    # clone public dependencies
    - name: vcs import
      if: ${{ env.DO_BUILD == 'true' }}
      shell: bash
      working-directory: ${{ env.ROS_WS }}
      run: vcs import src < src/${PACKAGE_NAME}/.github/dependencies.repos
    - run: colcon graph
      if: ${{ env.DO_BUILD == 'true' }}
      shell: bash
      working-directory: ${{ env.ROS_WS }}
    - name: rosdep install
      if: ${{ env.DO_BUILD == 'true' }}
      shell: bash
      working-directory: ${{ env.ROS_WS }}
      run: |
        rosdep update;
        rosdep install  -i -y --rosdistro ${ROS_DISTRO} --skip-keys "pybind11" --from-paths src
    - name: colcon build
      if: ${{ env.DO_BUILD == 'true' }}
      shell: bash
      working-directory: ${{ env.ROS_WS }}
      env:
        CC: ${{ env.CC }}
        CXX: ${{ env.CXX }}
        LINKER_PATH: ${{ env.LINKER_PATH }}
        COMPILER_FLAG: ${{ matrix.COMPILER_FLAG }}
      run: |
        . /opt/ros/${ROS_DISTRO}/setup.bash;
        colcon build --cmake-args -DCMAKE_LINKER=${LINKER_PATH} \
            ${COMPILER_FLAG} \
            --packages-up-to ${PACKAGE_NAME} \
            --event-handlers=console_direct+;
    - name: colcon test
      if: ${{ env.DO_BUILD == 'true' }}
      shell: bash
      working-directory: ${{ env.ROS_WS }}
      run: |
        . /opt/ros/${ROS_DISTRO}/setup.bash;
        colcon test --packages-select ${PACKAGE_NAME} --event-handlers=console_direct+;
        colcon test-result --verbose;
